version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo
    volumes:
      - vol_mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      my_network:
        ipv4_address: 172.16.200.2

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    container_name: mongo-express
    depends_on:
      - mongo
    networks:
      my_network:
        ipv4_address: 172.16.200.3

volumes:
  vol_mongo_data:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24